### ISSUE TITLE
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

### ISSUE THREAD

**Issue by krtschmr** [Sailias/bitcoin_payable#11]
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

we need to change the migrations and inherit from `< ActiveRecord::Migration[5.1]`

Rails 5.1 is coming and that will raise exception

**Comment by Sailias** [comment]
fixed by https://github.com/Sailias/bitcoin_payable/tree/releases/rails-5.1
