### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by krtschmr** [Sailias/bitcoin_payable#12]
DEPRECATION WARNING: Passing a class to the `class_name` is deprecated and will raise an ArgumentError in Rails 5.2. It eagerloads more classes than necessary and potentially creates circular dependencies. Please pass the class name as a string: `has_many :bitcoin_payments, class_name: 'BitcoinPayable::BitcoinPayment'` (called from has_bitcoin_payments at /home/tim/.rvm/gems/ruby-2.3.1/bundler/gems/bitcoin_payable-5e9c8f829c12/lib/bitcoin_payable/has_bitcoin_payment.rb:11)

starting 5.2 will raise the error, 5.1 starts the deprecation

**Comment by Sailias** [comment]
fixed by https://github.com/Sailias/bitcoin_payable/tree/releases/rails-5.1
