### ISSUE TITLE
segwit addresses

### ISSUE THREAD

**Issue by krtschmr** [Sailias/bitcoin_payable#17]
did anything change for the MPK with the new segwit addresses? i didn't find any changes, so i assume everything is the same for the masterpublickey?

**Comment by starcharles** [comment]
masterpublickey(extended pubkey) will change in the segwit address.

root deriviation path is different in ordinal bip44 HD-wallet keys(m/44/ ////)

but for segwit addresses m/49/  should be used.
money-tree is not implemented for segwit , so I think money-tree is the first one to do these new tasks.

**Comment by krtschmr** [comment]
money-tree still doesn't support segwit? 

bummer....
