### ISSUE TITLE
Supporting other cryptocurrencies (Litecoin, Ethereum etc)

### ISSUE THREAD

**Issue by mhluska** [Sailias/bitcoin_payable#26]
I would like to support purchases in other cryptocurrencies in my app. I'm not sure if I should extend this gem with Litecoin support or roll a new one. It seems like a lot of this code is general enough to support other coins (with the exception of the MoneyTree and adapter stuff). What do you think @Sailias ?

FYI my main motivation is avoiding huge bitcoin fees currently. The items for sale on my site are typically $5-$20 USD which makes $5 fees kind of painful.

**Comment by artfullyContrived** [comment]
Won't this require a name change for the gem?

**Comment by Sailias** [comment]
@artfullyContrived https://github.com/Sailias/cryptocoin_payable

Yes
