### ISSUE TITLE
Specify price in Satoshi

### ISSUE THREAD

**Issue by faissaloo** [Sailias/bitcoin_payable#43]
Would be nice not to be tied to the dollar since I don't live in the US.

**Comment by Sailias** [comment]
You can change the currency to your country’s currency in your country’s currency. 

This gem updates the amount of bitcoin owed based on the conversion rate.  You couldn’t do that if it wasn’t based off fiat.

**Comment by maesitos** [comment]
@faissaloo there's a fork of the code that allows to also have multiple fiat denominations if you'd like to sell with different currencies using the same gem https://github.com/maesitos/bitcoin_payable
