### ISSUE TITLE
A class was passed to `:class_name` but we are expecting a string

### ISSUE THREAD

**Issue by Ispirett** [Sailias/bitcoin_payable#45]
Hi! First of all thanks for the hard work that has gone into this project, it has helped me understand making transactions with bitcoin and ruby.

I am receiving this error with rails 6.1.1 and ruby 2.7.2 I'm also using docker.
This error occurs when using the `has_bitcoin_payments` method.
I believe I have fixed this and would like to make a pull request.

**Comment by Sailias** [comment]
@Ispirett go ahead and submit a pull request. I might have to be part of a different branch for that version of rails.

**Comment by Ispirett** [comment]
> @Ispirett go ahead and submit a pull request. I might have to be part of a different branch for that version of rails.

Hey! how are you? Do you mean like 6.1.1 branch ?
