### ISSUE TITLE
Breaking with 4.2.6 and Spree

### ISSUE THREAD

**Issue by krtschmr** [Sailias/bitcoin_payable#7]
Not sure if Spree or Rails is the issue.

`NoMethodError: protected method `around_validation' called for #<StateMachine::Machine:0x000000033ffba8>`

**Comment by krtschmr** [comment]
Problem is the depedency of state_machine. 
simply removing that will keep `spree 3.1.0` and `rails 4.2.6` stable.

**Comment by Sailias** [comment]
@krtschmr 

Obviously state_machine cannot be removed as a dependency from the library.
This is a really old and known error in state_machine.

https://github.com/pluginaweek/state_machine/issues/251

You can fix this by adding this code to your project as stated in the issue above.

config/initializers/state_machine_patch.rb
```
module StateMachine
  module Integrations
     module ActiveModel
        public :around_validation
     end

     module ActiveRecord
        public :around_save
     end
  end
end
```

**Comment by krtschmr** [comment]
thanks. removing it works like a charme. i'll use the AR patch to keep 
it stable for updates.thanks!
