### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by Ooglermarc** [Sailias/bitcoin_payable#8]
Hi @Sailias 

I am trying to install the bitcoin_payable gem on a Rails 5 app. 

In my gem file I added the gem as:
`gem 'bitcoin_payable'`

And I get the following error message:
` bitcoin_payable x86-mingw32 was resolved to 0.0.1, which depends on
      rails (~> 4.0.0) x86-mingw32`

**Comment by Sailias** [comment]
Are you using the RubyGems version or did you add the gem to your Gemfile with:

`gem 'bitcoin_payable', git: 'https://github.com/Sailias/bitcoin_payable', branch: 'master'`

The RubyGems version is old and probably still has the `Gemfile.lock` included.

**Comment by Ooglermarc** [comment]
Thank you @Sailias, the installation from the repository did work, however I am now receiving SSL related issues, seems to be linked to money-tree/lib/openssl_extensions. I will create another project and install money tree on its own to see if I still get this issue. Thanks again.
